name: 'AWS SAM action docker image'
description: 'Docker image to run AWS SAM command in a docker image and deploy in AWS'
inputs:
    command:
        description: 'AWS CLI commands to run'
        required: true

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.command }}
        
                
